name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  AUTH: ${{secrets.VP_DEPLOY_USER}}:${{secrets.VP_DEPLOY_SECRET}}
  REPO: ${{secrets.DEPLOY_REPO}}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Cache Rust Artifacts
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install GStreamer
        run: |
          sudo apt update && \
          sudo apt install -y \
            libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
            gstreamer1.0-plugins-base gstreamer1.0-plugins-good \
            gstreamer1.0-plugins-bad gstreamer1.0-libav libgstrtspserver-1.0-dev libges-1.0-dev
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Deploy Dev
        run: |
          curl -XPOST -u "${AUTH}" -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${REPO}/dispatches -d '{"event_type": "dev"}'
